const STATUS_SUCCESS = "success";
const STATUS_ERROR = "fail";

const TICKET_VALID_TIME = {
    SINGLE_TICKET : 75,
    TWENTY_FOUR_HOURS_TICKET : 1,
    SEVEN_DAYS_TICKET : 7,
  }
  

export { STATUS_SUCCESS, STATUS_ERROR, TICKET_VALID_TIME };
